<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Counter-Covid CTIS - Test Report</title>

    <!-- Icon -->
    <link rel="icon" href="/images/favicon.webp">
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }
        .title {
            text-align: center;
        }
    </style>

</head>

<body id="page-top">

    <div class="container-fluid">
        <h3>Counter-Covid CTIS Test Report</h3>
        <h4>Test Report Generated By {{Auth::user()->name}}</h4>
        <br><br><br>
        <div class="title">
            <h2>List of Covid-19 Tests Conducted on <br>{{Auth::user()->testCenter}}</h2>
        </div> 
        <br>
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Test ID</th>
                    <th>Patient Name</th>
                    <th>Test Type</th>
                    <th>Test Date</th>
                    <th>Responsible Tester</th>
                    <th>Test Status</th>
                    <th>Test Result</th>
                </tr>
            </thead>
            <tbody>
                @foreach($covidTests as $key=> $data)
                @if ($data->testCenter == Auth::user()->testCenter)
                    <tr>                
                        <td>{{$data->id}}</td>
                        <td>{{$data->patientName}}</td>
                        <td>{{$data->testType}}</td>
                        <td>{{$data->date}}</td>
                        <td>{{$data->testerName}}</td>
                        <td>{{$data->status}}</td>  
                        <td>
                            @if($data->status != "Completed")
                                {{"Not Tested"}}
                            @else
                                {{$data->result}}
                            @endif
                        </td>
                    </tr>
                @endif
            @endforeach
            </tbody>
        </table>
    </div>
</body>

</html>
